server:
  port: 8081
eureka:
  client:
    service-url:
      192.168.5.24: http://localhost:8761/eureka

spring:
  application:
    name: adrian-gateway

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    user-management:
      url: http://localhost:8080