server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}

spring:
  application:
    name: adrian-zuul-gateway

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    user-management:
      url: http://user-management:8080